[package]
name = "organize-fs"
version = "0.1.0"
edition = "2024"

[dependencies]
clap = { version = "4.2", features = ["derive"] }
walkdir = "2.3"
chrono = {version = "0.4", features = ["clock"]}
humansize = "2.1.3"
anyhow = "1.0"
dialoguer = "0.12"
dirs = "5.0"