[package]
name = "backup-fs"
version = "0.1.0"
edition = "2024"

[dependencies]
clap = { version = "4.5", features = ["derive"] }
walkdir = "2.5"
anyhow = "1.0"
fs_extra = "1.3"
chrono = "0.4"
dialoguer = "0.12"
zip = "5.1.1"
dirs = "5.0"